const modalities = [
  {
    'modality1': 'Experimental',
    'modality2': 'Plate',
    'modality3': '',
    'modality4': '',
    'columnName': 'Plate',
    'simplify': 'Plate',
    'order': 1,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'Western blot',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'Western',
    'order': 1,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'Northern blot',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'Northern',
    'order': 2,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'RT_PCR',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'RT_PCR',
    'order': 3,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'Whole Mount Embryo',
    'columnName': 'Light',
    'simplify': 'Whole Mount',
    'order': 1,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'In Situ Hybridization',
    'columnName': 'Light',
    'simplify': 'InSitu',
    'order': 2,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'Other LM',
    'columnName': 'Light',
    'simplify': 'Other',
    'order': 3,
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Electron',
    'modality4': 'Transmission EM',
    'columnName': 'Electron',
    'simplify': 'Transmission',
    'order': 1,
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Electron',
    'modality4': 'Scanning EM',
    'columnName': 'Electron',
    'simplify': 'Scanning',
    'order': 2,
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Whole Mount Embryo',
    'columnName': 'Fluorescence',
    'simplify': 'Whole Mount',
    'order': 3,
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Reporter Genes and Immunohistochemistry',
    'columnName': 'Fluorescence',
    'simplify': 'Reporter Genes & IHC',
    'order': 2,
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'EFIC',
    'columnName': 'Fluorescence',
    'simplify': 'EFIC',
    'order': 1,
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Other FM',
    'columnName': 'Fluorescence',
    'simplify': 'Other',
    'order': 4,
  },{
    'modality1': 'Other',
    'modality2': '',
    'modality3': '',
    'modality4': '',
    'columnName': 'Other',
    'simplify': 'Other',
    'order': 1,
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'X-Ray',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'X-Ray',
    'order': 3,
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'MRI and CT',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'MRI & CT',
    'order': 1,
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'Photographs',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'Photos',
    'order': 2,
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Macromolecule Sequence',
    'modality3': 'DNA',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'DNA Seq',
    'order': 1,
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Macromolecule Sequence',
    'modality3': 'Protein',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'Protein Seq',
    'order': 2,
  },{
    'modality1': 'Molecular Structure',
    'modality2': '3D Structure',
    'modality3': '',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': '3D Struc',
    'order': 3,
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Chemical Structure',
    'modality3': '',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'Chemical Struc',
    'order': 4,
  },,{
    'modality1': 'Graphics',
    'modality2': 'Bar Chart',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Bar Chart',
    'order': 1,
  },{
    'modality1': 'Graphics',
    'modality2': 'Line Chart',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Line Chart',
    'order': 2,
  },{
    'modality1': 'Graphics',
    'modality2': 'Scatterplot',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Scatterplot',
    'order': 3,
  },{
    'modality1': 'Graphics',
    'modality2': 'Pathway',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Pathway',
    'order': 4,
  },{
    'modality1': 'Graphics',
    'modality2': 'Other Diagram',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Other Diagram',
    'order': 5,
  }
]

module.exports = { modalities }
