const modalities = [
  {
    'modality1': 'Experimental',
    'modality2': 'Plate',
    'modality3': '',
    'modality4': '',
    'columnName': 'Plate',
    'simplify': 'Plate',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'Western blot',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'Western',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'Northern blot',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'Northern',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Gel',
    'modality3': 'RT_PCR',
    'modality4': '',
    'columnName': 'Gel',
    'simplify': 'RT_PCR',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'Whole Mount Embryo',
    'columnName': 'Light',
    'simplify': 'Whole Mount',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'In Situ Hybridization',
    'columnName': 'Light',
    'simplify': 'InSitu',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Light',
    'modality4': 'Other LM',
    'columnName': 'Light',
    'simplify': 'Other',
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Electron',
    'modality4': 'Transmission EM',
    'columnName': 'Electron',
    'simplify': 'Transmission',    
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Electron',
    'modality4': 'Scanning EM',
    'columnName': 'Electron',
    'simplify': 'Scanning',
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Whole Mount Embryo',
    'columnName': 'Fluorescence',
    'simplify': 'Whole Mount',
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Reporter Genes and Immunohistochemistry',
    'columnName': 'Fluorescence',
    'simplify': 'Reporter Genes & IHC',
  },{
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'EFIC',
    'columnName': 'Fluorescence',
    'simplify': 'EFIC',
  },
  {
    'modality1': 'Experimental',
    'modality2': 'Microscopy',
    'modality3': 'Fluorescence',
    'modality4': 'Other FM',
    'columnName': 'Fluorescence',
    'simplify': 'Other',
  },{
    'modality1': 'Other',
    'modality2': '',
    'modality3': '',
    'modality4': '',
    'columnName': 'Other',
    'simplify': 'Other',
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'X-Ray',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'X-Ray',
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'MRI and CT',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'MRI & CT',
  },{
    'modality1': 'Organs and Organisms',
    'modality2': 'Photographs',
    'modality3': '',
    'modality4': '',
    'columnName': 'Organisms',
    'simplify': 'Photos',
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Macromolecule Sequence',
    'modality3': 'DNA',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'DNA',
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Macromolecule Sequence',
    'modality3': 'Protein',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'Protein',
  },{
    'modality1': 'Molecular Structure',
    'modality2': '3D Structure',
    'modality3': '',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': '3D',
  },{
    'modality1': 'Molecular Structure',
    'modality2': 'Chemical Structure',
    'modality3': '',
    'modality4': '',
    'columnName': 'Molecular Structure',
    'simplify': 'Chemical Structure',
  },{
    'modality1': 'Graphics',
    'modality2': 'Diagram',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Diagram',
  },{
    'modality1': 'Graphics',
    'modality2': 'Bar Chart',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Bar Chart',
  },{
    'modality1': 'Graphics',
    'modality2': 'Line Chart',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Line Chart',
  },{
    'modality1': 'Graphics',
    'modality2': 'Scatterplot',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Scatterplot',
  },{
    'modality1': 'Graphics',
    'modality2': 'Scatterplot',
    'modality3': '',
    'modality4': '',
    'columnName': 'Graphics',
    'simplify': 'Other',
  }
]

module.exports = { modalities }
